name: Test
on: [push, pull_request, workflow_dispatch]
jobs:

  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: ./
        with:
          channel: latest/stable

      - name: Launch container
        run: |
          lxc launch ubuntu:

  channel:
    name: Channel
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: ./
        with:
          # use a channel that is not the default on ubuntu-latest
          channel: 5.21/candidate

      - name: Check LXD version
        shell: bash
        run: |
          [[ $(lxd version) == 5.21* ]]

      - name: Launch container
        run: |
          lxc launch ubuntu:

  preinstalled:
    name: Preinstalled
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: ./

      - name: Check LXD version
        shell: bash
        run: |
          [[ $(lxd version) == 4.0.9 ]]

      - name: Launch container
        run: |
          lxc launch ubuntu:

  latest-stable:
    name: Install latest/stable
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: |
          sudo snap install yq

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: ./
        with:
          channel: latest/stable

      - name: Check LXD version
        shell: bash
        run: |
          set -eux
          LATEST_STABLE_VERSION=$(snap info lxd | yq '.channels.latest/stable' | awk -F'-' '{print $1}')
          [[ $(lxd version) == $LATEST_STABLE_VERSION ]]

      - name: Launch container
        run: |
          lxc launch ubuntu:
